### ISSUE TITLE
Remplacer banner homepage

### ISSUE THREAD

**Issue by renatomartins** [asso-pea/mois-vegane.ch#12]
Sébastien a crée une nouvelle image:
https://drive.google.com/open?id=0B8FTDRa-F4ETWjlSbDNwX0ZfMjg

**Comment by sephii** [comment]
@renatomartins d'après ce que je vois c'est fait ça non?

**Comment by renatomartins** [comment]
C'est un peu different.

Actuellement:
![ekrankopio de 2017-10-11 10-32-12](https://user-images.githubusercontent.com/925119/31429900-8f9516f4-ae6f-11e7-85d8-deddbe787035.png)

Nouvelle:
![ekrankopio de 2017-10-11 10-32-30](https://user-images.githubusercontent.com/925119/31429922-9f5e0604-ae6f-11e7-95b3-ea0c498da3ea.png)

**Comment by sephii** [comment]
Ah oui c'est mieux!
